version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: fly-site
      POSTGRES_USER: fly-site
      POSTGRES_PASSWORD: fly-site
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
